<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mydemodistribution"
 *
 * Auto generated by Extension Builder 2015-07-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'My Distribution',
	'description' => '',
	'category' => 'distribution',
	'author' => 'Wolfgang Wagner',
	'author_email' => 'wwagner@jweiland.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.6.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.2-7.9.99',
			'fluid_styled_content' => '',
			'version' => '',
			'recycler' => '',
			'filemetadata' => '',
			'powermail' => '',
			'realurl' => '',
		),
		'conflicts' => array(
			'css_styled_content' => '',
		),
		'suggests' => array(
		),
	),
);