<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "demodistribution"
 *
 * Auto generated by Extension Builder 2017-12-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'My Distribution',
    'description' => '',
    'category' => 'distribution',
    'author' => 'Wolfgang Wagner',
    'author_email' => 'wwagner@jweiland.net',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.9',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'fluid_styled_content' => '',
            'version' => '',
            'recycler' => '',
            'filemetadata' => '',
            'powermail' => '',
            'realurl' => '',
        ],
        'conflicts' => [
          'css_styled_content' => '',
        ],
        'suggests' => [],
    ],
];
